
process_medium_data <- function(media_wd, 
                                medium_name,
                                bacteria_counts,
                                biomass) {
  
  cat("medium name: ", medium_name, "\n")
  cat("number of bacteria: ", bacteria_counts, "(cell)", "\n")
  cat("biomass per cell: ", biomass, "(pgDW)", "\n")
  
  # Step 1: Check if the processed .tsv file exists; if not, process the raw data
  if ( !file.exists(paste0(media_wd, "/", medium_name, ".tsv")) ) {

    # Read the raw medium data from the text file
    # diet generated by the Diet Designer on https://www.vmh.life
    diet_data <- read.table(
      paste0(media_wd, "/", medium_name, ".txt"),
      sep = "\n",
      stringsAsFactors = FALSE
    )

    # Initialize an empty data frame for metabolite data
    df <- data.frame(
      Metabolite = character(),
      g_day_person = numeric(),
      Molecular_Weight = numeric(),
      Flux_in_mmol_human_day = numeric(),
      exchange_reaction = character(),
      stringsAsFactors = FALSE
    )

    # Extract data in chunks of 5 rows for each metabolite
    for (i in seq(1, nrow(diet_data), 5)) {
      df <- rbind(df, data.frame(
        Metabolite = diet_data[i, 1],
        g_day_person = as.numeric(diet_data[i + 1, 1]),
        Molecular_Weight = as.numeric(diet_data[i + 2, 1]),
        Flux_in_mmol_human_day = as.numeric(diet_data[i + 3, 1]),
        exchange_reaction = diet_data[i + 4, 1]
      ))
    }

    # Save the structured data to a .tsv file
    write.table(
      df,
      file = paste0(media_wd, "/", medium_name, ".tsv"),
      quote = FALSE,
      sep = '\t',
      col.names = NA
    )
  }
  
  # Step 2: Load the processed medium data
  adaptedDietConstraints <- read.delim2(paste0(media_wd, "/", medium_name, ".tsv"))
  adaptedDietConstraints <- subset(adaptedDietConstraints, select = -X)
  adaptedDietConstraints$g_day_person <- as.double(adaptedDietConstraints$g_day_person)
  adaptedDietConstraints$Molecular_Weight <- as.double(adaptedDietConstraints$Molecular_Weight)
  adaptedDietConstraints$Flux_in_mmol_human_day <- as.double(adaptedDietConstraints$Flux_in_mmol_human_day)
  
  # Clean the 'exchange_reaction' column by replacing or removing problematic characters
  adaptedDietConstraints$exchange_reaction <- gsub("\\[", "_", adaptedDietConstraints$exchange_reaction)  # Replace '[' with '_'
  adaptedDietConstraints$exchange_reaction <- gsub("\\]", "", adaptedDietConstraints$exchange_reaction)   # Remove ']'
  adaptedDietConstraints$exchange_reaction <- gsub("\\(", "_", adaptedDietConstraints$exchange_reaction)  # Replace '(' with '_'
  adaptedDietConstraints$exchange_reaction <- gsub("\\)", "", adaptedDietConstraints$exchange_reaction)   # Remove ')'
  
  # Step 3: Handle essential metabolites
  # Define the list of essential metabolites required for growth in AGORA models
  essentialMetabolites <- c(
    "EX_12dgr180(e)", "EX_26dap_M(e)", "EX_2dmmq8(e)", "EX_2obut(e)", "EX_3mop(e)", "EX_4abz(e)", "EX_4hbz(e)",
    "EX_ac(e)", "EX_acgam(e)", "EX_acmana(e)", "EX_acnam(e)", "EX_ade(e)", "EX_adn(e)", "EX_adocbl(e)", 
    "EX_ala_D(e)", "EX_ala_L(e)", "EX_amet(e)", "EX_amp(e)", "EX_arab_D(e)", "EX_arab_L(e)", "EX_arg_L(e)",
    "EX_asn_L(e)", "EX_btn(e)", "EX_ca2(e)", "EX_cbl1(e)", "EX_cgly(e)", "EX_chor(e)", "EX_chsterol(e)",
    "EX_cit(e)", "EX_cl(e)", "EX_cobalt2(e)", "EX_csn(e)", "EX_cu2(e)", "EX_cys_L(e)", "EX_cytd(e)", 
    "EX_dad_2(e)", "EX_dcyt(e)", "EX_ddca(e)", "EX_dgsn(e)", "EX_fald(e)", "EX_fe2(e)", "EX_fe3(e)", "EX_fol(e)", 
    "EX_for(e)", "EX_gal(e)", "EX_glc_D(e)", "EX_gln_L(e)", "EX_glu_L(e)", "EX_gly(e)", "EX_glyc(e)", 
    "EX_glyc3p(e)", "EX_gsn(e)", "EX_gthox(e)", "EX_gthrd(e)", "EX_gua(e)", "EX_h(e)", "EX_h2o(e)", 
    "EX_h2s(e)", "EX_his_L(e)", "EX_hxan(e)", "EX_ile_L(e)", "EX_k(e)", "EX_lanost(e)", "EX_leu_L(e)", 
    "EX_lys_L(e)", "EX_malt(e)", "EX_met_L(e)", "EX_mg2(e)", "EX_mn2(e)", "EX_mqn7(e)", "EX_mqn8(e)", 
    "EX_nac(e)", "EX_ncam(e)", "EX_nmn(e)", "EX_no2(e)", "EX_ocdca(e)", "EX_ocdcea(e)", "EX_orn(e)", 
    "EX_phe_L(e)", "EX_pheme(e)", "EX_pi(e)", "EX_pnto_R(e)", "EX_pro_L(e)", "EX_ptrc(e)", "EX_pydx(e)", 
    "EX_pydxn(e)", "EX_q8(e)", "EX_rib_D(e)", "EX_ribflv(e)", "EX_ser_L(e)", "EX_sheme(e)", "EX_so4(e)", 
    "EX_spmd(e)", "EX_thm(e)", "EX_thr_L(e)", "EX_thymd(e)", "EX_trp_L(e)", "EX_ttdca(e)", "EX_tyr_L(e)", 
    "EX_ura(e)", "EX_val_L(e)", "EX_xan(e)", "EX_xyl_D(e)", "EX_zn2(e)", "EX_glu_D(e)", "EX_melib(e)", 
    "EX_chtbs(e)", "EX_metsox_S_L(e)", "EX_hdca(e)", "EX_gam(e)", "EX_indole(e)", "EX_glcn(e)", "EX_coa(e)", 
    "EX_man(e)", "EX_fum(e)", "EX_succ(e)", "EX_no3(e)", "EX_ins(e)", "EX_uri(e)", "EX_drib(e)", "EX_pime(e)", 
    "EX_lac_L(e)", "EX_glypro(e)", "EX_urea(e)", "EX_duri(e)", "EX_h2(e)", "EX_mal_L(e)", "EX_tre(e)", 
    "EX_orot(e)", "EX_glymet(e)", "EX_glyleu(e)", "EX_pydx5p(e)", "EX_so3(e)", "EX_nh4(e)"
  )
  
  essentialMetabolites <- gsub("\\(", "_", essentialMetabolites)
  essentialMetabolites <- gsub("\\)", "", essentialMetabolites)
  
  missingUptakes <- setdiff(essentialMetabolites, adaptedDietConstraints$exchange_reaction)
  
  for (metabolite in missingUptakes) {
    adaptedDietConstraints <- rbind(adaptedDietConstraints, data.frame(
      Metabolite = NA,
      g_day_person = NA,
      Molecular_Weight = NA,
      Flux_in_mmol_human_day = 0.1,
      exchange_reaction = metabolite,
      stringsAsFactors = FALSE
    ))
  }
  
  # Step 4: Handle unmapped compounds
  # Allow uptake of certain dietary compounds that are currently not mapped in the Diet Designer
  UnmappedCompounds <- c('EX_asn_L(e)', 'EX_gln_L(e)', 'EX_crn(e)', 'EX_elaid(e)', 'EX_hdcea(e)',
                         'EX_dlnlcg(e)', 'EX_adrn(e)', 'EX_hco3(e)', 'EX_sprm(e)', 'EX_carn(e)',
                         'EX_7thf(e)', 'EX_Lcystin(e)', 'EX_hista(e)', 'EX_orn(e)', 'EX_ptrc(e)',
                         'EX_creat(e)', 'EX_cytd(e)', 'EX_so4(e)')
  
  UnmappedCompounds <- gsub("\\(", "_", UnmappedCompounds)
  unmappedCompounds <- gsub("\\)", "", UnmappedCompounds)
  
  to_remove <- intersect(adaptedDietConstraints$exchange_reaction, unmappedCompounds)
  adaptedDietConstraints <- adaptedDietConstraints[!adaptedDietConstraints$exchange_reaction %in% to_remove, ]
  
  for (compound in unmappedCompounds) {
    adaptedDietConstraints <- rbind(adaptedDietConstraints, data.frame(
      Metabolite = NA,
      g_day_person = NA,
      Molecular_Weight = NA,
      Flux_in_mmol_human_day = 50,
      exchange_reaction = compound,
      stringsAsFactors = FALSE
    ))
  }
  
  # Step 5: Add choline if missing
  if (!any(grepl("EX_chol_e", adaptedDietConstraints$exchange_reaction))) {
    adaptedDietConstraints <- rbind(adaptedDietConstraints, data.frame(
      Metabolite = NA,
      g_day_person = NA,
      Molecular_Weight = NA,
      Flux_in_mmol_human_day = 41.251,
      exchange_reaction = "EX_chol_e",
      stringsAsFactors = FALSE
    ))
  }
  
  # Step 6: Handle micronutrients
  # List of micronutrients that require minimum uptake levels for model stability
  Micronutrients <- c('EX_adocbl(e)', 'EX_vitd2(e)', 'EX_vitd3(e)', 'EX_psyl(e)', 'EX_gum(e)',
                      'EX_bglc(e)', 'EX_phyQ(e)', 'EX_fol(e)', 'EX_5mthf(e)', 'EX_q10(e)', 
                      'EX_retinol_9_cis(e)', 'EX_pydxn(e)', 'EX_pydam(e)', 'EX_pydx(e)', 
                      'EX_pheme(e)', 'EX_ribflv(e)', 'EX_thm(e)', 'EX_avite1(e)', 'EX_pnto_R(e)', 
                      'EX_na1(e)', 'EX_cl(e)', 'EX_k(e)', 'EX_pi(e)', 'EX_zn2(e)', 'EX_cu2(e)', 
                      'EX_btn(e)')
  
  Micronutrients <- gsub("\\(", "_", Micronutrients)
  micronutrients <- gsub("\\)", "", Micronutrients)
  
  for ( i in 1:nrow(adaptedDietConstraints) ) {
    exchange <- adaptedDietConstraints$exchange_reaction[i]
    flux <- adaptedDietConstraints$Flux_in_mmol_human_day[i]
    
    if ( exchange %in% micronutrients && abs(flux) <= 0.1 ) {
      adaptedDietConstraints$Flux_in_mmol_human_day[i] <- flux * 100
    }
    
    if (exchange == 'EX_pnto_R_e' && abs(flux) < 0.1) {
      adaptedDietConstraints$Flux_in_mmol_human_day[i] <- 0.1
    }
    
    if (exchange %in% c('EX_fol_e', 'EX_arab_L_e', 'EX_xyl_D_e', 'EX_amp_e', 'EX_nh4_e', 'EX_cobalt2_e') && abs(flux) < 1) {
      adaptedDietConstraints$Flux_in_mmol_human_day[i] <- 1
    }
  }
  
  # Clean up Metabolite column
  adaptedDietConstraints$Metabolite <- gsub("EX_", "", adaptedDietConstraints$exchange_reaction)
  adaptedDietConstraints$Flux_in_mmol_human_day = adaptedDietConstraints$Flux_in_mmol_human_day/bacteria_counts*biomass
  
  cat("metabolites in medium: ", dim(adaptedDietConstraints)[1], "\n")
  
  return(adaptedDietConstraints)
}
