#' Generate a PNPRO XML from an arc table – DEBUG build
#'
#' @param arc_df     Data-frame containing columns
#'                   `place, transition, direction, multiplicity, command`
#' @param pnpro_out  Path to write the *.PNPRO* file.
#' @export
generate_pnpro <- function(arc_df, pnpro_out) {

  message("\n─── 0) sanity checks ──────────────────────────────────────")
  message("   distinct places     : ", length(unique(arc_df$place)))
  message("   distinct transitions: ", length(unique(arc_df$transition)))
  message("   arc rows            : ", nrow(arc_df))

  # ------------------------------------------------------------------
  # 1) unique places / transitions
  # ------------------------------------------------------------------
  places      <- unique(arc_df$place)
  transitions <- unique(arc_df$transition)

  command_df <- arc_df[!is.na(arc_df$command) & arc_df$command != "",
                       c("transition", "command")]
  command_df <- command_df[!duplicated(command_df$transition), ]
  commands   <- setNames(command_df$command, command_df$transition)

  # ------------------------------------------------------------------
  # 2) header + nodes (auto-layout)
  # ------------------------------------------------------------------
  xml_header <- '<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by generate_pnpro() -->\n<project name="Generated" version="121">
  <gspn name="PetriNet" zoom="50">
    <nodes>'

  # places
  places_xml <- ""
  y <- 3
  for (pl in places) {
    places_xml <- paste0(places_xml,
      sprintf('\n      <place name="%s" x="6.0" y="%.1f" label-x="0" label-y="0"/>',
              pl, y))
    y <- y + 2
  }

  # transitions
  transitions_xml <- ""
  y <- 7; x <- 4
  for (tr in transitions) {
    delay_attr <- if (tr %in% names(commands)) {
      cmd <- gsub('"', '&quot;', commands[tr])
      sprintf('delay="%s"', cmd)
    } else 'delay="1.0"'

    transitions_xml <- paste0(transitions_xml,
      sprintf('\n      <transition name="%s" %s x="%.1f" y="%.1f" '
              ,'label-x="0" label-y="0" nservers-x="0.5" type="EXP"/>',
              tr, delay_attr, x, y))
    x <- x + 3
    if (x > 15) { x <- 4; y <- y + 3 }
  }

  # ------------------------------------------------------------------
  # 3) edges / arcs
  # ------------------------------------------------------------------
  edges_header <- '\n    </nodes>\n    <edges>'
  edges_xml    <- ""
  skipped      <- 0

  for (i in seq_len(nrow(arc_df))) {
    row <- arc_df[i, ]
    if (is.na(row$direction) ||
        !row$direction %in% c("INPUT", "OUTPUT")) {
      message("❗ row ", i,
              " skipped – invalid direction: ", row$direction)
      skipped <- skipped + 1
      next
    }

    mult_attr <- if (!is.na(row$multiplicity) && row$multiplicity > 1)
                   sprintf(' mult="%d"', row$multiplicity) else ""

    edges_xml <- if (row$direction == "INPUT") {
      paste0(edges_xml,
        sprintf('\n      <arc head="%s" kind="INPUT"%s tail="%s"/>',
                row$transition, mult_attr, row$place))
    } else {
      paste0(edges_xml,
        sprintf('\n      <arc head="%s" kind="OUTPUT"%s tail="%s"/>',
                row$place,      mult_attr, row$transition))
    }
  }
  message("✔ arcs rendered : ", nrow(arc_df) - skipped)
  if (skipped) message("⚠ skipped arcs : ", skipped)

  # ------------------------------------------------------------------
  # 4) footer
  # ------------------------------------------------------------------
  xml_footer <- '\n    </edges>
  </gspn>
  <measures gspn-name="PetriNet" name="Measures" simplified-UI="false">
    <assignments/>
    <greatspn/>
    <formulas>
      <formula comment="Basic statistics" language="STAT"/>
      <formula comment="All PN measures"  language="ALL"/>
    </formulas>
  </measures>
</project>'

  xml_content <- paste0(
    xml_header, places_xml, transitions_xml, edges_header, edges_xml,
    xml_footer)

  # ------------------------------------------------------------------
  # 5) write
  # ------------------------------------------------------------------
  dir.create(dirname(pnpro_out), recursive = TRUE, showWarnings = FALSE)
  writeLines(xml_content, pnpro_out)
  message("✓ PNPRO written to: ", pnpro_out)

  invisible(pnpro_out)
}

