# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

read_cobra_mat <- function(path) {
    .Call(`_epimodFBAfunctions_read_cobra_mat`, path)
}

writeModelCpp <- function(S, react_id, met_id, obj_coef, lowbnd, uppbnd, rb, gene_assoc, model_name, write, wd, bioMax = -1, bioMean = -1, bioMin = -1, pFBAFlag = -1L) {
    invisible(.Call(`_epimodFBAfunctions_writeModelCpp`, S, react_id, met_id, obj_coef, lowbnd, uppbnd, rb, gene_assoc, model_name, write, wd, bioMax, bioMean, bioMin, pFBAFlag))
}

